# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1461135898);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1461136018);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1461135537);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1461135778);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1461135658);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1461136138);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 266240);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 30);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150930122151");
user_pref("browser.slowStartup.averageTime", 2771);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20150930122151");
user_pref("browser.startup.homepage_override.mstone", "41.0.1");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1461135481666");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1461135493265");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1461221893265");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1461135429972");
user_pref("datareporting.policy.firstRunTime", "1453871938191");
user_pref("datareporting.sessions.current.activeTicks", 54);
user_pref("datareporting.sessions.current.firstPaint", 4947);
user_pref("datareporting.sessions.current.main", 762);
user_pref("datareporting.sessions.current.sessionRestored", 5311);
user_pref("datareporting.sessions.current.startTime", "1461135414672");
user_pref("datareporting.sessions.current.totalTime", 892);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.prunedIndex", 1);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:41.0.1");
user_pref("extensions.getAddons.cache.lastUpdate", 1461135908);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "41.0.1");
user_pref("extensions.lastPlatformVersion", "41.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"41.0.1\",\"st\":1453854478000,\"mt\":1443617717000}}}");
user_pref("gecko.buildID", "20150930122151");
user_pref("gecko.mstone", "41.0.1");
user_pref("idle.lastDailyNotification", 1461136479);
user_pref("media.gmp-manager.buildID", "20150930122151");
user_pref("media.gmp-manager.lastCheck", 1461135486);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 24674);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1461135415);
user_pref("toolkit.telemetry.cachedClientID", "856c5151-0db0-4fb0-93bd-ae1d9b6837ee");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
